server:
  port: 8090
spring:
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedHeaders: "*"
            allowedMethods:
              - GET
              - POST
              - DELETE
              - PUT
              - OPTIONS
      routes:
        - id: via
          uri: http://localhost:8084/
          predicates:
            - Path=/api/via/**
        - id: maestro
          uri: http://localhost:8083/
          predicates:
            - Path=/api/maestro/**
        - id: tipomaestro
          uri: http://localhost:8083/
          predicates:
            - Path=/api/tipomaestro/**
        - id: contribuyente
          uri: http://localhost:8082/
          predicates:
            - Path=/api/contribuyente/**