server:
  port: 8090

spring:
  cloud:
    gateway:
      routes:
        - id: via
          uri: http://localhost:8082/
          predicates:
            - Path=/via/**
          - id: maestro
          uri: http://localhost:8083/
          predicates:
            - Path=/maestro/*
          -id: contribuyente
          uri: http://localhost:8084/
          predicates:
            - Path=/contribuyente/*